import try_excedpt

try_excedpt.simula_erros()